mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - ".:/workspace"
  links:
    - "mysql"
    - "redis"

redis:
  image: redis:latest
  command: redis-server
  ports:
    - '6379:6379'
  volumes:
    - 'redis:/data'